version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Instalando dependências com Node 20..."
      - npm install
  build:
    commands:
      - echo "Iniciando compilação (Ignorando erros de checagem para deploy)..."
      # O segredo: usamos 'npx vite build' direto para pular o 'tsc' que está travando o build
      - npx vite build
  post_build:
    commands:
      - echo "Sincronizando com o S3..."
      - aws s3 sync dist/ s3://portfolio-cloud-edivaldo-v1 --delete
      - echo "Limpando cache do CloudFront..."
      - aws cloudfront create-invalidation --distribution-id E3NA5CGW54I377 --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: dist