version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependências..."
      - npm install
  build:
    commands:
      - echo "Transformando TypeScript em JavaScript (Build)..."
      - npm run build
  post_build:
    commands:
      - echo "Sincronizando a pasta de DISTRIBUIÇÃO com o S3..."
      # IMPORTANTE: O comando agora aponta para a pasta 'dist' (ou 'build')
      - aws s3 sync dist/ s3://portfolio-cloud-edivaldo-v1 --delete
      - echo "Limpando cache do CloudFront..."
      - aws cloudfront create-invalidation --distribution-id E3NA5CGW54I377 --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: dist
