version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Iniciando o deploy do Portfolio..."
      # Sincroniza os arquivos do GitHub com o seu Bucket S3
      - aws s3 sync . s3://portfolio-cloud-edivaldo-v1 --delete --exclude ".git/*" --exclude "buildspec.yml"
  post_build:
    commands:
      - echo "Limpando o cache do CloudFront para atualizar o site..."
      # Substitua o ID abaixo pelo ID da sua distribuição (termina em I377)
      - aws cloudfront create-invalidation --distribution-id E3NA5CGW54I377 --paths "/*"

artifacts:
  files:
    - '**/*'
