version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependências para o ambiente de Build..."
      - npm install
  build:
    commands:
      - echo "Iniciando a compilação (Transformando TSX em JS)..."
      # O comando '|| true' evita que o build pare se houver apenas avisos de lint
      - npm run build
  post_build:
    commands:
      - echo "Sincronizando arquivos compilados com o S3..."
      # IMPORTANTE: Verifique se sua pasta de saída é 'dist' ou 'build'
      # Se for React comum, mude 'dist/' para 'build/'
      - aws s3 sync dist/ s3://portfolio-cloud-edivaldo-v1 --delete
      - echo "Limpando o cache do CloudFront para atualizar o site..."
      - aws cloudfront create-invalidation --distribution-id E3NA5CGW54I377 --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: dist